# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 28, 19, 45, 30, 483843)),
        ),
    ]
