# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20171218_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 14, 49, 16, 999305)),
        ),
    ]
