# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_auto_20171218_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sort_description',
            new_name='short_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 14, 50, 9, 228967)),
        ),
    ]
