# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 17:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_auto_20171218_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 12, 6, 22, 960211)),
        ),
    ]
